version: "3"
services:
  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker-data/docker-minio:/var/lib/postgresql/data
    ports:
      - 5432:5432
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - 9000:9000
    volumes:
      - ./docker-data/docker-minio:/data
    command: server ./docker-data/docker-minio
  deploy:
    image: python:3.6.7
    ports:
      - 1234:1234
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/usr/src/app
    command: tail -f /dev/null