version: "3"
services:
  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
    ports:
      - 5432:5432
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - 9000:9000
    command: server ./docker-data/docker-minio
  filldata:
    build: .
    depends_on:
      - postgres
      - minio
    command: filldata
  model:
    build: .
    depends_on:
      - filldata
    command: model
  deploy:
    build: .
    ports:
      - 1234:1234
    depends_on:
      - model
    command: deploy
  redis:
    image: redis:3.2.7
  flower:
    image: puckel/docker-airflow:1.10.3
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower
  webserver:
    build:
      context: .
      dockerfile: Airflow-Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  scheduler:
    build:
      context: .
      dockerfile: Airflow-Dockerfile
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
    command: scheduler
  worker:
    build:
      context: .
      dockerfile: Airflow-Dockerfile
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
    command: worker